Data = [1,5,7,4,9,8,9,4,3,2,1,1,5,6,0,8,3]
print(f"Data angka{Data}")

Jumlah_Data1 = Data.count(1)
Jumlah_Data2 = Data.count(2)
Jumlah_Data3 = Data.count(3)
Jumlah_Data4 = Data.count(4)
Jumlah_Data5 = Data.count(5)
Jumlah_Data6 = Data.count(6)
Jumlah_Data7 = Data.count(7)
Jumlah_Data8 = Data.count(8)
Jumlah_Data9 = Data.count(9)
Jumlah_Data0 = Data.count(0)

print(f"Jumlah Data1 = {Jumlah_Data1}")
print(f"Jumlah Data2 = {Jumlah_Data2}")
print(f"Jumlah Data3 = {Jumlah_Data3}")
print(f"Jumlah Data4 = {Jumlah_Data4}")
print(f"Jumlah Data5 = {Jumlah_Data5}")
print(f"Jumlah Data6 = {Jumlah_Data6}")
print(f"Jumlah Data7 = {Jumlah_Data7}")
print(f"Jumlah Data8 = {Jumlah_Data8}")
print(f"Jumlah Data9 = {Jumlah_Data9}")
print(f"Jumlah Data0 = {Jumlah_Data0}")
